---

###
### Enable sudo (required for docker service)
###
sudo: required


###
### Language
###
language: minimal


###
### Install requirements
###
install:
  - retry() {
      for ((n=0; n<60; n++)); do
        echo "[${n}] ${*}";
        if eval "${*}"; then
          return 0;
        fi;
        sleep 1;
      done;
      return 1;
    }


###
### Checks
###
script:
  - retry make lint
  - retry make test
